name=HydroNode-Library
version=1.1.0
author=Felix Knoll
maintainer=Felix Knoll <contact@knollfelix.de>
sentence=Send sensor data and receive backend events for HydroNode projects.
paragraph=Easy API client for HydroNode sensors and actuators, with event callback system, HMAC-SHA256 auth, TLS with bundled root CAs, NTP time sync and optional WiFi helper. ESP32 only.
category=Communication
url=https://github.com/TexhFexLabs/HydroNode-Library
architectures=esp32
license=MIT
depends=WiFiManager, ArduinoJson, ArduinoHttpClient, NTPClient, base64_arduino, Crypto
